### ISSUE TITLE
atomsWithQuery's status return promise instead of query result (ApolloQueryResult) on first load

### ISSUE THREAD

**Issue by lxcid** [Aslemammad/jotai-apollo#13]
I have this wierd bug where it return promise in the first call before it correctly return the query result object (loading, data, etc)

I check the return value of 

https://github.com/jotaijs/jotai-apollo/blob/1e34fda90b6a16c2323ab22c7498e70ac48088a9/src/common.ts#L52

that seems to be the behavior.

**Comment by dai-shi** [comment]
@Aslemammad ?

**Comment by Aslemammad** [comment]
Hey, just busy here a bit, i'll get to this when I have time! 

@dai-shi is it because the new version of jotai?

it'd good to have a repro possibly.

**Comment by dai-shi** [comment]
If it works differently with a previous version of Jotai, it may be.

**Comment by it-nalon** [comment]
I tried reproducing the bug updating all the dependencies in the example but it seems to work correctly: [https://stackblitz.com/edit/react-ts-mfiehg?file=index.tsx](https://stackblitz.com/edit/react-ts-mfiehg?file=index.tsx)

**Comment by it-nalon** [comment]
I updated the Rick&Morty example and it seems to work to me: [https://stackblitz.com/edit/react-ts-mfiehg?file=index.tsx](https://stackblitz.com/edit/react-ts-mfiehg?file=index.tsx)

**Comment by lxcid** [comment]
Sorry for late reply, i figure out the repo, if you use it inside an atom. it will have that behavior. using your example

![CleanShot 2024-09-25 at 23 34 49](https://github.com/user-attachments/assets/6a57dea0-e7e6-43f0-84e0-8f101c249c38)

notice how the `status.loading` is undefined and `status` is promise before it become fully resolved.

**Comment by it-nalon** [comment]
@lxcid I think that's the expected behavior. Probably you should use an `async` atom instead of a normal one [https://jotai.org/docs/guides/async](https://jotai.org/docs/guides/async).

I've updated the example using an async atom instead: [https://stackblitz.com/edit/react-ts-mfiehg?file=index.tsx](https://stackblitz.com/edit/react-ts-mfiehg?file=index.tsx)

**Comment by lxcid** [comment]
ahh thanks for the quick response! My bad! Closing!
